### ISSUE TITLE
Utils

### ISSUE THREAD

**Issue by r00bal** [KamilSzafranski/goit-react-hw-03-phonebook#1]
https://github.com/KamilSzafranski/goit-react-hw-03-phonebook/blob/e02bcfc7da6e2f44be3eac1d8910f3552101e5b6/src/components/Storage/Local.js#L1-L18

Przerzuciłbym to do pliku utils. Można mieć oddzielny folder na utilsy dla całej apki  albo trzymać plik utils.js dla każdego komponentu w jego folderze (o ile jest potrzebny). To odrazu sugeruje, że znajdują się tam funkcje pomocnicze. Przy większych projektach poprawie to odnaleźć się w strukturze projektu.

**Comment by KamilSzafranski** [comment]
Poprawione :)
